# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Sunxiangkun lawyer
subtitle: 天与水违行，讼；君子以作事谋始
author: 孙祥坤律师
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://jusliver.cn      # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: Jusliver
email: sxklawyer@yeah.net
description: ""
keyword: ""
signature: false #show signature
signature-img:

# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
# github_username:    sherlockblaze
# twitter_username:   Demonbane_x
# facebook_username:  YenYuHsuan
# linkedin_username:  yu-hsuan-yen

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description-line1: "执业领域：公司金融、破产清算、刑事辩护、婚姻家庭"
sidebar-about-description-line2: "邮箱：sxklawyer@yeah.net"
sidebar-avatar: resources/img/header_img/DogFace.jpg
widgets:
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
#- category


recommended_posts:
  server: https://api.truelaurel.com
  timeoutInMillis: 10000
  internalLinks: 3
  externalLinks: 0
  autoDisplay: true,
  titleHtml: <span style="font-size:1.45em; color:gray">Recommened</span>

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Friends
friends: [
    {
        title: "SherlockBlaze's Blog",
        href: "https://sherlockblaze.com/"
    }
]


#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

search:
  path: search.xml
  field: post
  format: html
  limit: 17

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository:
    github: https://__GITHUB_TOKEN__@github.com/sxklawyer95/sxklawyer95.github.io.git
  branch: master

valine: true
valineAppId: __VISITORS_APPID__
valineAppKey: __VISITORS_APPKEY__
valineNotify: false
valineVerify: true
valinePlaceHolder: Let us talk more!!
valineAvatar: wavatar
valineGuestInfo: nick,mail,link
valinePageSize: 10
visitor: true
